### ISSUE TITLE
Mögliche Verbesserungen

### ISSUE THREAD

**Issue by openscript** [BWizard06/to-do-project#1]
Gerne möchte ich Dir Feedback zu diesem Projekt geben, da ich denke, dass Reviews sehr lehrreich sein können. 

- [ ] Konstanten auch wirklich als solche deklarieren: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L3
- [ ] Gestaltung (UI) und Logik strikte trennen: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L11-L15
- [ ] Funktionen brauchen, um den Code besser zu strukturieren: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L20
- [ ] Quellcode immer passend formatieren und einrücken, um die Übersicht zu behalten: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/index.html#L44
- [ ] Variabeln nur verwenden, wenn es sich auch wirklich nur um Variabeln handelt: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/login.js#L26
- [ ] Redundanzen vermeiden (bspw. eine Klasse für den Button erstellen und mehrfach verwenden): https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/styles.css#L11 https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/styles.css#L37
- [ ] Wie wäre es, wenn dafür eine Funktion geschrieben wird, welche solche Hinweise dem Benutzer anzeigt. `function sendNotification(message) {}` vielleicht? https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L13
- [ ] Die Commit Messages sind nicht einheitlich. Manchmal Deutsch manchmal nicht. Das Format unterscheidet sich.
  - https://www.conventionalcommits.org/en/v1.0.0/
  - https://cbea.ms/git-commit/
  - Bei einem anderen Projekt schauen, wie die das machen und lange machen es nicht alle gut: https://github.com/microsoft/vscode/commits/main

Diese Rückmeldung hat nichts mit der Bewertung des Projekts zu tun.

**Comment by BWizard06** [comment]
Hallo Robin,
Ich habe mir das Feedback angeschaut. Danke für die Tips, sie sind sehr hilfreich.
LG Ben

Von: Robin ***@***.***>
Gesendet: Dienstag, 18. Oktober 2022 14:38
An: BWizard06/to-do-project ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [BWizard06/to-do-project] Mögliche Verbesserungen (Full review) (Issue #1)


Gerne möchte ich Dir Feedback zu diesem Projekt geben, da ich denke, dass Reviews sehr lehrreich sein können.

  *   [ ] Konstanten auch wirklich als solche deklarieren: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L3
  *   [ ] Gestaltung (UI) und Logik strikte trennen: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L11-L15
  *   [ ] Funktionen brauchen, um den Code besser zu strukturieren: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L20
  *   [ ] Quellcode immer passend formatieren und einrücken, um die Übersicht zu behalten: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/index.html#L44
  *   [ ] Variabeln nur verwenden, wenn es sich auch wirklich nur um Variabeln handelt: https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/login.js#L26
  *   [ ] Redundanzen vermeiden (bspw. eine Klasse für den Button erstellen und mehrfach verwenden): https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/styles.css#L11 https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/styles.css#L37
  *   [ ] Passende Werkzeuge einsetzen. Hier wird Gestaltung mit Javascript umgesetzt, wobei CSS eigentlich für die Gestaltung verantwortlich ist. Mit CSS Keyframes könnte dies ohne Javascript umgesetzt werden https://github.com/BWizard06/to-do-project/blob/da4c1cacd72a53f54d4f15e971080c3cdfcce119/src/addTask.js#L13
  *   [ ] Die Commit Messages sind nicht einheitlich. Manchmal Deutsch manchmal nicht. Das Format unterscheidet sich.
     *   https://www.conventionalcommits.org/en/v1.0.0/
     *   https://cbea.ms/git-commit/
     *   Bei einem anderen Projekt schauen, wie die das machen und lange machen es nicht alle gut: https://github.com/microsoft/vscode/commits/main

Diese Rückmeldung hat nichts mit der Bewertung des Projekts zu tun.

-
